define([
  'vb/action/actionChain',
  'vb/action/actions',
  'vb/action/actionUtils',
], (
  ActionChain,
  Actions,
  ActionUtils
) => {
  'use strict';

  class emailTemplateAddEditAC extends ActionChain {

    /**
     * @param {Object} context
     */
    async run(context) {
      const { $page, $flow, $application, $constants, $variables } = context;

      let response;

      try {
        console.log("=== Email Template Save Started ===");
        console.log("Method:", $variables.method);

        console.log("Form Valid:", $variables.isFormValid);

        if ($variables.isFormValid === "valid") {
          
          // ✅ Set audit fields
          if ($variables.method === "POST") {
            console.log("Setting audit fields for new record");
            
            // ✅ Use template_id that was set before calling save
            // (Either from page parameter or generated by caller)
            if (!$variables.emailTemplateVar.template_id || $variables.emailTemplateVar.template_id === 0) {
              $variables.emailTemplateVar.template_id = $variables.key || 0;
            }
            
            console.log("Template ID for POST:", $variables.emailTemplateVar.template_id);
            
            $variables.emailTemplateVar.created_by = $application.user.fullName;
            $variables.emailTemplateVar.created_date = await $application.functions.getSysdate();
          }
          
          $variables.emailTemplateVar.last_updated_by = $application.user.fullName;
          $variables.emailTemplateVar.last_updated_date = await $application.functions.getSysdate();
          $variables.emailTemplateVar.last_updated_login = $application.user.email; // ✅ Changed to email

          console.log("✓ Audit fields set");

          // 🔐 Encrypt payload
          console.log("🔐 Encrypting payload...");
          console.log("Payload before encryption:", JSON.stringify($variables.emailTemplateVar, null, 2));
          
          const encryptedPayload = await $application.functions.encryptJs(
            $application.constants.secretKey,
            $variables.emailTemplateVar
          );

          $variables.encryptedBody.payload = encryptedPayload;
          
          console.log("✓ Payload encrypted");

          // 🔐 Encrypt headers
          console.log("🔐 Encrypting headers...");
          
          const headerCode = await $application.functions.encryptJs(
            $application.constants.secretKey,
            $variables.method
          );

          const headerId = await $application.functions.encryptJs(
            $application.constants.secretKey,
            $variables.key.toString()
          );

          console.log("✓ Headers encrypted");

          // 🌐 Call REST endpoint
          console.log("🌐 Calling REST endpoint: postEmailProcess");
          console.log("Operation:", $variables.method);

          response = await Actions.callRest(context, {
            endpoint: 'Application/postEmailProcess',
            headers: {
              'x-session-code': headerCode,
              'x-session-id': headerId,
            },
            body: $variables.encryptedBody,
          });

          console.log("✓ REST call completed");
          console.log("Response Status:", response.body.P_ERR_CODE);
          console.log("Response Message:", response.body.P_ERR_MSG);

          // ✅ Handle success response
          if (response.body.P_ERR_CODE === "S") {
            
            await Actions.fireNotificationEvent(context, {
              summary: response.body.P_ERR_MSG || ($variables.method === "POST" ? 
                'Template created successfully' : 'Template updated successfully'),
              displayMode: "transient",
              type: "confirmation",
            });

            // Update variables based on operation
            if ($variables.method === "POST") {
              console.log("✓ Insert successful - switching to UPDATE mode");
              $variables.method = "PUT";
              
              // ✅ Get encrypted template_id from response header
              const encryptedTemplateId = response.headers.get('x-session-id');
              console.log("Encrypted template_id from response:", encryptedTemplateId);
              
              if (encryptedTemplateId) {
                // ✅ Call special endpoint to get template data using encrypted ID
                console.log("🔄 Fetching template data using encrypted ID...");
                
                const getTemplateResponse = await Actions.callRest(context, {
                  endpoint: 'Application/getEmailTemplateDtl',
                  headers: {
                    'x-session-id': encryptedTemplateId,
                  },
                });
                
                console.log("Get template response:", JSON.stringify(getTemplateResponse.body, null, 2));
                
                if (getTemplateResponse.body.count > 0) {
                  
                  // Populate template variable with fetched data
                  $variables.emailTemplateVar = getTemplateResponse.body.items[0];
                  
                  // ✅ Update key to raw template_id
                  $variables.key = $variables.emailTemplateVar.template_id;
                  
                  console.log("✓ Template data loaded");
                  console.log("✓ Template ID (raw):", $variables.key);
                  console.log("✓ Template Name:", $variables.emailTemplateVar.template_name);
                  
                } else {
                  console.error("✗ Failed to fetch template data");
                  
                  await Actions.fireNotificationEvent(context, {
                    summary: 'Warning',
                    message: 'Template saved but failed to reload data',
                    displayMode: 'transient',
                    type: 'warning',
                  });
                }
                
              } else {
                console.error("✗ No template_id returned from POST");
              }
              
            } else if ($variables.method === "PUT") {
              console.log("✓ Update successful");
              
              // Reload header data for PUT operations
              console.log("🔄 Reloading header data...");
              await Actions.callChain(context, {
                chain: 'loadHeaderAC',
              });
              console.log("✓ Header data reloaded");
            }

          } else {
            // ❌ Handle error response
            console.error("✗ Save failed:", response.body.P_ERR_MSG);
            
            await Actions.fireNotificationEvent(context, {
              summary: response.body.P_ERR_MSG || 'Failed to save template',
              displayMode: "persist",
              type: "error",
            });
          }
          
        } else {
          // ❌ Form validation failed
          console.log("✗ Form validation failed");
          
          // Show validation messages
          const vg = document.getElementById("email-template-validation");

          if (vg) {
            if (vg.valid === "invalidHidden") {
              vg.showMessages();
              console.log("✓ Showing hidden validation messages");
            }
            if (vg.valid !== "valid") {
              vg.focusOn("@firstInvalidShown");
              console.log("✓ Focused on first invalid field");
            }
          }

          // Warn user
          await Actions.fireNotificationEvent(context, {
            summary: "Please fix the highlighted errors before saving.",
            displayMode: "transient",
            type: "warning",
          });
        }

      } catch (error) {
        console.error("✗ Error in save action chain:", error);
        
        await Actions.fireNotificationEvent(context, {
          summary: 'Save Error',
          message: 'Failed to save email template: ' + error.message,
          type: 'error',
          displayMode: 'persist'
        });
      }

      return response?.body?.P_ERR_CODE;
    }
  }

  return emailTemplateAddEditAC;
});