define([
  'vb/action/actionChain',
  'vb/action/actions',
  'vb/action/actionUtils',
], (
  ActionChain,
  Actions,
  ActionUtils
) => {
  'use strict';

  class onHdrSaveAction extends ActionChain {

    /**
     * @param {Object} context
     * @returns {string} 'S' for complete success, 'E' for any error or partial success
     */
    async run(context) {
      const { $page, $flow, $application, $constants, $variables } = context;

      // ═══════════════════════════════════════════════════════════════════
      // STEP 1: Prepare payload (use generalInfoVar - TABLE structure)
      // ═══════════════════════════════════════════════════════════════════
      let payload = { ...$variables.generalInfoVar };
      payload.supplier_name = $variables.generalInfoVar.supplier_name;
      payload.contractor_id = $variables.generalInfoVar.contractor_id;
      
      // Update audit fields
      const currentUser = $application.user.username || 'SYSTEM';
      const sessionId = $application.user.sessionId || 'WEB_SESSION';
      
      payload.last_updated_by = currentUser;
      payload.last_updated_login = currentUser;
      
      // For CREATE mode, add created_by and remove general_id
      if ($variables.pNavCode === 'CREATE') {
        payload.created_by = currentUser;
        payload.object_version_num = 0;
        delete payload.general_id; // Will be auto-generated by sequence
      }
      
      // ═══════════════════════════════════════════════════════════════════
      // STEP 2: Determine method and key based on mode
      // ═══════════════════════════════════════════════════════════════════
      let temp_method;
      let temp_key;
      
      if ($variables.pNavCode === 'EDIT') {
        temp_method = 'PUT';
        temp_key = $variables.generalInfoVar.general_id; // Primary key for update
      } else {
        temp_method = 'POST';
        temp_key = await Actions.callChain(context, {
          chain: 'application:encryptAC',
          params: {
            input: '0',
          },
        });
      }

      // ═══════════════════════════════════════════════════════════════════
      // STEP 3: Encrypt payload, method, and key
      // ═══════════════════════════════════════════════════════════════════
      let enc_payload = await Actions.callChain(context, {
        chain: 'application:encryptAC',
        params: {
          input: payload, // Use TABLE structure payload
        },
      });

      let enc_key = await Actions.callChain(context, {
        chain: 'application:encryptAC',
        params: {
          input: temp_key,
        },
      });

      let enc_method = await Actions.callChain(context, {
        chain: 'application:encryptAC',
        params: {
          input: temp_method,
        },
      });

      // ═══════════════════════════════════════════════════════════════════
      // STEP 4: Call REST API
      // ═══════════════════════════════════════════════════════════════════
      try {
        const response = await Actions.callRest(context, {
          endpoint: 'PDD/postPmispddGeneralProcess',
          headers: {
            'x-session-code': enc_method,
            'x-session-id': enc_key,
          },
          body: { "payload": enc_payload },
        });

        // ═══════════════════════════════════════════════════════════════════
        // STEP 5: Handle response
        // ═══════════════════════════════════════════════════════════════════
        
        // Check response body for success/error status
        if (response && response.body && response.body.P_ERR_CODE === 'S') {
          // Success - Fire notification
          await Actions.fireNotificationEvent(context, {
            summary: $variables.pNavCode === 'CREATE' 
              ? 'Record created successfully' 
              : 'Record updated successfully',
            message: response.body.P_ERR_MSG || 'Operation completed successfully.',
            type: 'confirmation',
            displayMode: 'transient',
          });
          
          // ═══════════════════════════════════════════════════════════════════
          // STEP 6: ALWAYS CALL getbyid (for both CREATE and EDIT modes)
          // ═══════════════════════════════════════════════════════════════════
          
          let temp_tender_id = await Actions.callChain(context, {
            chain: 'application:encryptAC',
            params: {
              input: $variables.generalInfoVar.tender_id,
            },
          });

          try {
            console.log('Calling getbyid to refresh data after save...');
            
            const getByIdResponse = await Actions.callRest(context, {
              endpoint: 'PDD/getPmispddGeneralGetbyid',
              headers: {
                'x-session-id': temp_tender_id,
              },
            });
            
            // Check if getbyid was successful
            if (getByIdResponse && getByIdResponse.body && getByIdResponse.body.count === 1) {
              const item = getByIdResponse.body.items[0];
              console.log('getbyid successful, refreshing UI data...');
              console.table("++1 After getbyid: ", item);
              
              // Map VIEW data to TABLE structure for generalInfoVar
              $variables.generalInfoVar = this.mapViewToTable(item);
              console.table("++2 After view2table mapped: ", $variables.generalInfoVar);

              // Store full VIEW data (with display names)
              $variables.generalInfoVar.tender_id = item.tender_id;
              $variables.generalInfoVar.tender_name = item.tender_name;
              $variables.generalInfoVar.tender_number = item.tender_number;
              $variables.generalInfoVar.ora_project_id = item.ora_project_id;
              $variables.generalInfoVar.ora_project_name = item.ora_project_name;
              $variables.generalInfoVar.ora_project_number = item.ora_project_number;
              $variables.generalInfoVar.supplier_name = item.supplier_name;
              $variables.generalInfoVar.general_id = item.general_id;
              $variables.generalInfoVar.object_version_num = item.object_version_num;

              console.table("++3 After getbyid assigned: ", $variables.generalInfoVar);
              
              // Ensure mode is EDIT after successful save
              $variables.pNavCode = 'EDIT';
              
              console.log('Data refreshed successfully. Mode:', $variables.pNavCode);
              
              // ✅ RETURN SUCCESS - Complete success (saved + reloaded)
              return 'S';
              
            } else {
              console.error('Failed to retrieve record after save');
              
              await Actions.fireNotificationEvent(context, {
                summary: 'Warning',
                message: 'Record saved but failed to reload latest data. Please refresh the page.',
                type: 'warning',
                displayMode: 'persist',
              });
              
              // ❌ RETURN ERROR - Data saved but reload failed
              return 'E';
            }
            
          } catch (getByIdError) {
            console.error('Error calling getbyid after save:', getByIdError);
            
            await Actions.fireNotificationEvent(context, {
              summary: 'Warning',
              message: 'Record saved but failed to reload latest data. Please refresh the page.',
              type: 'warning',
              displayMode: 'persist',
            });
            
            // ❌ RETURN ERROR - Data saved but reload failed
            return 'E';
          }
          
        } else {
          // Error from backend
          await Actions.fireNotificationEvent(context, {
            summary: 'Save Failed',
            message: response.body.p_err_msg || 'Failed to save record. Please try again.',
            type: 'error',
            displayMode: 'persist',
          });
          
          // ❌ RETURN ERROR
          return 'E';
        }
        
      } catch (error) {
        // Network or unexpected error
        console.error('Save error:', error);
        
        await Actions.fireNotificationEvent(context, {
          summary: 'Save Failed',
          message: 'An unexpected error occurred. Please try again.',
          type: 'error',
          displayMode: 'persist',
        });
        
        // ❌ RETURN ERROR
        return 'E';
      }
    }

    /**
     * Maps VIEW data (38 fields) to TABLE structure (27 fields)
     * Removes display name fields, keeps only IDs and data fields
     */
    mapViewToTable(viewData) {
      if (!viewData) return {};
      
      return {
        general_id: viewData.general_id,
        object_version_num: viewData.object_version_num || 1,
        ora_project_id: viewData.project_id || viewData.ora_project_id,
        tender_id: viewData.tender_id,
        phase_of_contract_id: viewData.phase_of_contract_id,
        contractor_id: viewData.contractor_id,
        project_desc: viewData.project_desc,
        original_amount: viewData.original_amount,
        budget: viewData.budget,
        project_type_id: viewData.project_type_id,
        section_id: viewData.section_id,
        sector: viewData.sector,
        stage: viewData.stage,
        status_id: viewData.status_id,
        comments: viewData.comments,
        scope_of_work: viewData.scope_of_work,
        anticipated_contract_value: viewData.anticipated_contract_value,
        source_of_fund_id: viewData.source_of_fund_id,
        potential_saving: viewData.potential_saving,
        region_id: viewData.region_id,
        pmu: viewData.pmu,
        additional_info: viewData.additional_info,
        created_by: viewData.created_by,
        created_date: viewData.created_date,
        last_updated_by: viewData.last_updated_by,
        last_updated_date: viewData.last_updated_date,
        last_updated_login: viewData.last_updated_login
      };
    }
  }

  return onHdrSaveAction;
});